setwd("/home/scott/Documents/R/forecasting/docs/gjopen-review-2019")
library(dplyr)
scores <- read.csv("data/gjopen-scores-2019.csv", skip=0, header=TRUE)
scores$Date.Ended <- as.Date(scores$Date.Ended, format = '%b %d, %Y %I:%M%p')
colnames(scores) <- c("Date", "Question", "Time", "Brier", "Median", "Accuracy")
scores$Time <- as.numeric(gsub("[\\%,]", "", scores$Time))
scores$Brier <- as.numeric(scores$Brier)
scores$Median <- as.numeric(scores$Median)
scores$Accuracy <- as.numeric(scores$Accuracy)
colnames(scores) <- c("Date", "Question", "Time", "Brier", "Median", "Accuracy")
scores$Question <- substr(scores$Question, 0, 40)
good <- filter(scores, Accuracy <= -.10 & Brier < 0.25 & Time > 75)
bad <- filter(scores, Accuracy >= .10 & Brier > 0.25 & Time > 75)
above <- filter(scores, Brier > 1)
View(good)
View(bad)
View(above)
View(scores)
